# Generated by Django 4.0.6 on 2022-07-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-name']},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'duration', 'price')},
        ),
    ]
